'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { demoWav } = require('../audio.js');
const { chromium } = require(process.env.SEREIN_PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.SEREIN_CHROMIUM_PATH || undefined,
    headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1100, height: 900 } });
    const errors = [], externalRequests = [];
    page.on('pageerror', error => errors.push(error.message));
    const previewUrl = process.env.SEREIN_PREVIEW_URL || pathToFileURL(path.join(__dirname, '..', 'preview.html')).href;
    page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(previewUrl).origin) externalRequests.push(request.url()); });
    await page.goto(previewUrl); await page.locator('#open-library').waitFor();
    assert.equal(await page.locator('.page-kicker').count(), 0);
    const screenshots = process.env.SEREIN_SCREENSHOT_DIR;
    if (screenshots) await page.screenshot({path: path.join(screenshots, 'serein-home.png')});
    await page.locator('#open-library').click();
    assert.equal(await page.locator('input[type=checkbox]').count(), 0);
    await page.locator('[data-track="funky-house"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime > .15);
    assert.ok(await page.locator('audio').evaluate(a => a.duration > 60));
    await page.locator('#play-pause').click(); assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    await page.locator('#seek').fill('20'); assert.ok(await page.locator('audio').evaluate(a => a.currentTime >= 19));
    await page.locator('#play-pause').click(); await page.waitForFunction(() => !document.querySelector('audio').paused);
    if (screenshots) await page.screenshot({path: path.join(screenshots, 'serein-library.png')});
    await page.locator('[data-track="synthwave-house-loop"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').duration > 45 && document.querySelector('audio').duration < 55);
    await page.locator('#audio-files').setInputFiles({name: 'Owned song.wav', mimeType: 'audio/wav', buffer: Buffer.from(demoWav(220, 8))});
    assert.equal(await page.locator('[data-track]').count(), 1);
    await page.locator('[data-track="file-1"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime > .15);
    await page.locator('#prepare').click(); assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    await page.getByRole('heading', {name: 'Ready to connect.'}).waitFor(); await page.locator('#attach').click();
    await page.locator('#library-tab').click();
    assert.equal(await page.locator('[data-track]').isDisabled(), true);
    assert.equal(await page.locator('#add-songs').isDisabled(), true);
    assert.equal(await page.locator('#player').isVisible(), false);
    await page.locator('#deck-tab').click(); await page.locator('#ejected').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#prepare').click(); await page.getByRole('heading', {name: 'Ready to connect.'}).waitFor();
    await page.locator('#attach').click(); await page.locator('#interrupt').click();
    await page.getByRole('heading', {name: 'Check before using.'}).waitFor();
    await page.locator('#library-tab').click(); assert.equal(await page.locator('[data-track]').isDisabled(), true);
    await page.locator('#deck-tab').click(); await page.locator('#recover').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#fail').click(); await page.locator('#prepare').click();
    await page.getByRole('heading', {name: 'Check before using.'}).waitFor(); await page.locator('#recover').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#prepare').click(); await page.locator('#cancel').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor(); await page.locator('#library-tab').click();
    await page.locator('#audio-files').setInputFiles({name: '<img src=x onerror=alert(1)>.wav', mimeType: 'audio/wav', buffer: Buffer.from(demoWav(330, 2))});
    assert.equal(await page.locator('.track img').count(), 0); assert.equal(await page.locator('[data-track]').count(), 2);
    await page.locator('#audio-files').setInputFiles({name: 'Broken.wav', mimeType: 'audio/wav', buffer: Buffer.from('invalid audio')});
    await page.locator('[data-track="file-3"]').click();
    await page.getByRole('status').filter({hasText: 'could not play'}).waitFor();
    assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    await page.locator('#home-tab').click(); await page.locator('#spotify').click();
    await page.getByRole('status').filter({hasText: 'Preview only'}).waitFor();
    await page.setViewportSize({width: 360, height: 800});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    assert.deepEqual(errors, []); assert.deepEqual(externalRequests, []);
    console.log('Passed both house tracks, pause/resume/seek, local-file import/playback, handoff/eject, recovery, failure, cancellation, escaped filenames, invalid audio, Spotify placeholder and mobile layout. No JS errors or external requests.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
