'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.SEREIN_PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.SEREIN_CHROMIUM_PATH || undefined,
    headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1100, height: 820 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const externalRequests = [];
    const previewUrl = process.env.SEREIN_PREVIEW_URL || pathToFileURL(path.join(__dirname, '..', 'preview.html')).href;
    page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(previewUrl).origin) externalRequests.push(request.url()); });
    await page.goto(previewUrl);
    await page.getByRole('heading', { name: 'Make it yours.' }).waitFor();
    const screenshotRoot = process.env.SEREIN_SCREENSHOT_DIR;
    if (screenshotRoot) await page.screenshot({ path: path.join(screenshotRoot, 'serein-home.png') });
    await page.getByRole('button', { name: 'Spotify Open the official app' }).click();
    await page.getByRole('status').filter({ hasText: 'Preview only' }).waitFor();
    await page.getByRole('button', { name: /Your DJ library/ }).click();
    await page.locator('[data-track="03"]').uncheck();
    await page.getByRole('button', { name: 'Prepare 2 tracks for deck' }).click();
    await page.getByRole('heading', { name: 'Ready to connect.' }).waitFor();
    await page.getByRole('button', { name: 'Simulate deck connection', exact: true }).click();
    await page.getByRole('heading', { name: 'Music with the deck.' }).waitFor();
    if (screenshotRoot) await page.screenshot({ path: path.join(screenshotRoot, 'serein-deck.png') });
    await page.locator('#library-tab').click();
    for (const input of await page.locator('[data-track]').all()) assert.equal(await input.isDisabled(), true);
    assert.equal(await page.locator('#prepare').isDisabled(), true);
    await page.locator('#deck-tab').click();
    await page.getByRole('button', { name: 'Deck ejected — return library' }).click();
    await page.getByRole('heading', { name: 'Bring your music.' }).waitFor();
    await page.locator('#library-tab').click();
    assert.equal(await page.locator('[data-track="03"]').isChecked(), false);
    assert.equal(await page.locator('[data-track="01"]').isDisabled(), false);
    await page.getByRole('button', { name: 'Prepare 2 tracks for deck' }).click();
    await page.getByRole('heading', { name: 'Ready to connect.' }).waitFor();
    await page.getByRole('button', { name: 'Simulate deck connection', exact: true }).click();
    await page.getByRole('button', { name: 'Simulate unexpected unplug' }).click();
    await page.getByRole('heading', { name: 'Check before using.' }).waitFor();
    await page.locator('#library-tab').click();
    assert.equal(await page.locator('[data-track="01"]').isDisabled(), true);
    await page.locator('#deck-tab').click();
    await page.getByRole('button', { name: 'Simulate check and restore' }).click();
    await page.getByRole('heading', { name: 'Bring your music.' }).waitFor();
    await page.getByRole('button', { name: 'Fail next preparation' }).click();
    await page.getByRole('button', { name: 'Prepare 2 tracks', exact: true }).click();
    await page.getByRole('heading', { name: 'Check before using.' }).waitFor();
    await page.getByRole('button', { name: 'Simulate check and restore' }).click();
    await page.getByRole('heading', { name: 'Bring your music.' }).waitFor();
    await page.getByRole('button', { name: 'Prepare 2 tracks', exact: true }).click();
    await page.getByRole('button', { name: 'Return to library' }).click();
    await page.getByRole('heading', { name: 'Bring your music.' }).waitFor();
    await page.locator('#library-tab').click();
    await page.locator('[data-track="01"]').uncheck(); await page.locator('[data-track="02"]').uncheck();
    assert.equal(await page.locator('#prepare').isDisabled(), true);
    await page.setViewportSize({ width: 360, height: 800 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.locator('#home-tab').click();
    if (screenshotRoot) await page.screenshot({ path: path.join(screenshotRoot, 'serein-mobile.png'), fullPage: true });
    assert.deepEqual(errors, []); assert.deepEqual(externalRequests, []);
    console.log('Browser journeys passed: selection, normal eject, interruption/recovery, preparation failure, cancellation, empty selection, mobile layout. No JS errors or external requests.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
