'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { demoWav } = require('../audio.js');
const { chromium } = require(process.env.SEREIN_PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.SEREIN_CHROMIUM_PATH || undefined,
    headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1100, height: 900 } });
    const errors = [], externalRequests = [];
    page.on('pageerror', error => errors.push(error.message));
    const previewUrl = process.env.SEREIN_PREVIEW_URL || pathToFileURL(path.join(__dirname, '..', 'preview.html')).href;
    page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(previewUrl).origin) externalRequests.push(request.url()); });
    await page.goto(previewUrl); await page.locator('#open-library').waitFor();
    assert.equal(await page.locator('.page-kicker').count(), 0);
    const screenshots = process.env.SEREIN_SCREENSHOT_DIR;
    if (screenshots) await page.screenshot({path: path.join(screenshots, 'serein-home.png')});
    await page.locator('#open-library').click();
    assert.equal(await page.locator('input[type=checkbox]').count(), 0);
    await page.locator('[data-track="funky-house"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime > .15);
    assert.ok(await page.locator('audio').evaluate(a => a.duration > 60));
    await page.locator('#now-toggle').click(); assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    await page.locator('#seek').fill('20'); assert.ok(await page.locator('audio').evaluate(a => a.currentTime >= 19));
    await page.locator('#now-toggle').click(); await page.waitForFunction(() => !document.querySelector('audio').paused);
    if (screenshots) await page.locator('.device').screenshot({path: path.join(screenshots, 'serein-player-device.png')});
    await page.locator('#close-player').click();
    if (screenshots) await page.locator('.device').screenshot({path: path.join(screenshots, 'serein-library-device.png')});
    await page.locator('#open-player').click();
    assert.equal(await page.locator('#now-title').textContent(), 'Funky House');
    await page.locator('#next').click();
    await page.waitForFunction(() => document.getElementById('now-title').textContent === 'Synthwave House Loop' && !document.querySelector('audio').paused);
    await page.locator('#previous').click();
    await page.waitForFunction(() => document.getElementById('now-title').textContent === 'Funky House');
    await page.locator('#now-shuffle').click();
    assert.equal(await page.locator('#now-shuffle').getAttribute('aria-pressed'), 'true');
    await page.locator('#close-player').click();
    await page.locator('#library-shuffle').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused);
    assert.equal(await page.locator('#now-shuffle').getAttribute('aria-pressed'), 'true');
    await page.locator('#close-player').click();
    await page.locator('#library-play').click();
    assert.equal(await page.locator('#now-title').textContent(), 'Funky House');
    assert.equal(await page.locator('#now-shuffle').getAttribute('aria-pressed'), 'false');
    await page.locator('#close-player').click();
    await page.locator('[data-track="synthwave-house-loop"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').duration > 45 && document.querySelector('audio').duration < 55);
    await page.locator('#close-player').click();
    await page.locator('[data-view="playlists"]').click();
    await page.locator('#new-list').click();
    await page.locator('#list-name').fill('House favourites');
    await page.locator('input[name="song"][value="funky-house"]').check();
    await page.getByRole('button', {name: 'Save playlist', exact: true}).click();
    await page.locator('.collection-title').waitFor();
    assert.equal(await page.locator('[data-track]').count(), 1);
    await page.locator('#library-play').click();
    assert.equal(await page.locator('#now-title').textContent(), 'Funky House');
    await page.locator('#next').click();
    assert.equal(await page.locator('#now-title').textContent(), 'Funky House');
    await page.locator('#close-player').click();
    await page.locator('#edit-list').click();
    await page.locator('input[name="song"][value="synthwave-house-loop"]').check();
    await page.getByRole('button', {name: 'Save playlist', exact: true}).click();
    await page.locator('.collection-title').waitFor();
    assert.equal(await page.locator('[data-track]').count(), 2);
    await page.locator('#edit-list').click();
    await page.locator('input[name="song"][value="synthwave-house-loop"]').uncheck();
    await page.getByRole('button', {name: 'Save playlist', exact: true}).click();
    await page.locator('.collection-title').waitFor();
    assert.equal(await page.locator('[data-track]').count(), 1);
    await page.locator('#back-library').click();
    await page.locator('[data-view="setlists"]').click();
    await page.locator('#new-list').click();
    await page.locator('#list-name').fill('Opening set');
    for (const checkbox of await page.locator('input[name="song"]').all()) await checkbox.check();
    await page.getByRole('button', {name: 'Save setlist', exact: true}).click();
    await page.locator('.collection-title').waitFor();
    await page.locator('.order-list summary').click();
    await page.getByRole('button', {name: 'Move song 2 up', exact: true}).click();
    await page.waitForFunction(() => document.querySelector('[data-track]')?.dataset.track === 'synthwave-house-loop');
    assert.equal(await page.locator('[data-track]').first().getAttribute('data-track'), 'synthwave-house-loop');
    await page.locator('#edit-list').click();
    await page.locator('#list-name').fill('Warm-up set');
    await page.getByRole('button', {name: 'Save setlist', exact: true}).click();
    await page.locator('.collection-title').waitFor();
    await page.waitForFunction(() => document.querySelector('[data-track]')?.dataset.track === 'synthwave-house-loop');
    assert.equal(await page.locator('[data-track]').first().getAttribute('data-track'), 'synthwave-house-loop');
    if (await page.locator('.order-list').getAttribute('open') !== null) await page.locator('.order-list summary').click();
    if (screenshots) await page.locator('.device').screenshot({path: path.join(screenshots, 'serein-setlist-device.png')});
    await page.locator('#library-play').click();
    assert.equal(await page.locator('#now-title').textContent(), 'Synthwave House Loop');
    await page.locator('#next').click();
    await page.waitForFunction(() => document.getElementById('now-title').textContent === 'Funky House' && !document.querySelector('audio').paused);
    await page.locator('#close-player').click();
    await page.locator('#back-library').click();
    await page.locator('[data-view="songs"]').click();
    await page.locator('#audio-files').setInputFiles({name: 'Owned song.wav', mimeType: 'audio/wav', buffer: Buffer.from(demoWav(220, 8))});
    await page.locator('[data-track="file-1"]').waitFor();
    assert.equal(await page.locator('[data-track]').count(), 1);
    await page.locator('[data-track="file-1"]').click();
    await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime > .15);
    await page.locator('#deck-tab').click();
    await page.locator('#prepare').click(); assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    await page.getByRole('heading', {name: 'Ready to connect.'}).waitFor(); await page.locator('#attach').click();
    await page.locator('#library-tab').click();
    assert.equal(await page.locator('[data-track]').isDisabled(), true);
    assert.equal(await page.locator('#add-songs').isDisabled(), true);
    assert.equal(await page.locator('#library-play').isDisabled(), true);
    assert.equal(await page.locator('#library-shuffle').isDisabled(), true);
    assert.equal(await page.locator('#player').isVisible(), false);
    await page.locator('[data-view="playlists"]').click();
    assert.equal(await page.locator('#new-list').isDisabled(), true);
    await page.locator('[data-collection="list-1"]').click();
    assert.equal(await page.locator('#edit-list').isDisabled(), true);
    assert.equal(await page.locator('#library-play').isDisabled(), true);
    await page.locator('#back-library').click();
    await page.locator('[data-view="songs"]').click();
    await page.locator('#deck-tab').click(); await page.locator('#ejected').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#prepare').click(); await page.getByRole('heading', {name: 'Ready to connect.'}).waitFor();
    await page.locator('#attach').click(); await page.locator('#interrupt').click();
    await page.getByRole('heading', {name: 'Check before using.'}).waitFor();
    await page.locator('#library-tab').click(); assert.equal(await page.locator('[data-track]').isDisabled(), true);
    await page.locator('#deck-tab').click(); await page.locator('#recover').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#fail').click(); await page.locator('#prepare').click();
    await page.getByRole('heading', {name: 'Check before using.'}).waitFor(); await page.locator('#recover').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor();
    await page.locator('#prepare').click(); await page.locator('#cancel').click();
    await page.getByRole('heading', {name: 'Deck connection', exact: true}).waitFor(); await page.locator('#library-tab').click();
    await page.locator('#audio-files').setInputFiles({name: '<img src=x onerror=alert(1)>.wav', mimeType: 'audio/wav', buffer: Buffer.from(demoWav(330, 2))});
    await page.locator('[data-track="file-2"]').waitFor();
    assert.equal(await page.locator('.track img').count(), 2);
    assert.equal(await page.locator('.track img[src="x"]').count(), 0); assert.equal(await page.locator('[data-track]').count(), 2);
    // The actual ended event advances to the next queued song.
    await page.locator('#library-play').click();
    await page.waitForFunction(() => Number.isFinite(document.querySelector('audio').duration));
    await page.locator('audio').evaluate(a => { a.currentTime = a.duration - .1; });
    await page.waitForFunction(() => document.getElementById('now-title').textContent.startsWith('<img'));
    await page.locator('#close-player').click();
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jL1sAAAAASUVORK5CYII=', 'base64');
    const frame = (id, bytes) => { const h = Buffer.alloc(10); h.write(id); h.writeUInt32BE(bytes.length, 4); return Buffer.concat([h, bytes]); };
    const body = Buffer.concat([
      frame('TIT2', Buffer.from('\x03Tagged track')),
      frame('TPE1', Buffer.from('\x03Local artist')),
      frame('TALB', Buffer.from('\x03Local album')),
      frame('APIC', Buffer.concat([Buffer.from([3]), Buffer.from('image/png\0'), Buffer.from([3,0]), png]))
    ]);
    const header = Buffer.from([73,68,51,3,0,0,0,0,0,0]);
    for (let i = 0; i < 4; i++) header[9-i] = (body.length >>> (i*7)) & 127;
    // Tag-only fixture tests local metadata/image rendering, not MP3 decoding.
    await page.locator('#audio-files').setInputFiles({name: 'Tagged.mp3', mimeType: 'audio/mpeg', buffer: Buffer.concat([header, body])});
    await page.locator('[data-track="file-3"]').waitFor();
    assert.ok((await page.locator('[data-track="file-3"] img').getAttribute('src')).startsWith('blob:'));
    await page.locator('[data-track="file-3"]').click();
    await page.waitForFunction(() => document.getElementById('now-art').naturalWidth === 1);
    assert.equal(await page.locator('#now-title').textContent(), 'Tagged track');
    assert.equal(await page.locator('#now-artist').textContent(), 'Local artist');
    assert.equal(await page.locator('.now-heading span').textContent(), 'Local album');
    await page.locator('#close-player').click();
    await page.locator('#audio-files').setInputFiles({name: 'Broken.wav', mimeType: 'audio/wav', buffer: Buffer.from('invalid audio')});
    await page.locator('[data-track="file-4"]').click();
    await page.getByRole('status').filter({hasText: 'could not play'}).waitFor();
    await page.waitForFunction(() => document.querySelector('audio').error && document.querySelector('audio').paused);
    await page.locator('#home-tab').click(); await page.locator('#spotify').click();
    await page.getByRole('status').filter({hasText: 'Preview only'}).waitFor();
    await page.setViewportSize({width: 360, height: 800});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.locator('#library-tab').click();
    await page.locator('[data-track="file-1"]').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    assert.deepEqual(errors, []); assert.deepEqual(externalRequests, []);
    console.log('Passed playlist create/edit/playback and ordered setlists, Library Play/Shuffle, full player, preview/embedded artwork and tagged metadata, mini-player reopen, next/previous, automatic queue advance, both house tracks, pause/resume/seek, local-file import/playback, handoff/eject, recovery, failure, cancellation, escaped filenames, invalid audio, Spotify placeholder and mobile layout. No JS errors or external requests.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
